In [142]:
import torch
import numpy as np
import time
import torch.nn as nn
device = 'cuda' if torch.cuda.is_available() else 'cpu'
from torch.nn import functional as F
print(device)

cuda


In [108]:
%%time
start_time = time.time()
#matrix operations here
zeros = torch.zeros(1,1)
end_time = time.time()

elapsed_time = end_time - start_time
print(f"{elapsed_time:8f}")

0.000440
CPU times: user 717 μs, sys: 5 μs, total: 722 μs
Wall time: 610 μs


In [110]:
#numpy CPU vs GPU

torch_rand1 = torch.rand(100, 100, 100, 100).to(device)
torch_rand2 = torch.rand(100, 100, 100, 100).to(device)
np_rand1 = torch.rand(100, 100, 100, 100)
np_rand2 = torch.rand(100, 100, 100, 100)

start_time = time.time()

rand = (torch_rand1 @ torch_rand2)

end_time = time.time()
elapsed_time = end_time - start_time
print(f"{elapsed_time:8f}")

start_time = time.time()

rand = np.multiply(np_rand1, np_rand2)
end_time = time.time()
elapsed_time = end_time - start_time
print(f"{elapsed_time:8f}")

0.001563
0.582765


In [111]:
probabilities = torch.tensor([0.1, 0.9])
samples = torch.multinomial(probabilities, num_samples=10, replacement=True)
print(samples)

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])


In [112]:
tensor = torch.tensor([1,2,3,4])
out = torch.cat((tensor, torch.tensor([5])), dim=0)
out

tensor([1, 2, 3, 4, 5])

In [113]:
out = torch.tril(torch.ones(5, 5))
out

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [114]:
out = torch.triu(torch.ones(5,5))
out

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [115]:
out = torch.zeros(5, 5).masked_fill(torch.tril(torch.ones(5, 5)) == 0, float('-inf'))
out

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [116]:
torch.exp(out)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [117]:
input = torch.zeros(2,3,4)
out = input.transpose(0,2)
out.shape

torch.Size([4, 3, 2])

In [118]:
tensor1 = torch.tensor([1,2,3])
tensor2 = torch.tensor([4,5,6])
tensor3 = torch.tensor([7,8,9])

stacked_tensor = torch.stack([tensor1, tensor2, tensor3])
stacked_tensor

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [119]:
import torch.nn as nn
sample = torch.tensor([10.,10.,10.])
linear = nn.Linear(3,3,bias=False)
print(linear(sample))

tensor([ 0.8690, -4.0887,  3.8938], grad_fn=<SqueezeBackward4>)


In [120]:
import torch.nn.functional as F

#Create a tensor
tensor1 = torch.tensor([1.0,2.0,3.0])
softmax_output = F.softmax(tensor1, dim=0)

print(softmax_output)

tensor([0.0900, 0.2447, 0.6652])


In [121]:
#Initialize an embedding layer
vocab_size = 80
embedding_dim = 6
embedding = nn.Embedding(vocab_size, embedding_dim)

#Create some input indices
input_indices = torch.LongTensor([1, 5, 3, 2])

#Apply the embedding layer
embedded_output = embedding(input_indices)

#The output will be a tensor of shape (4,100), where 4 is the number of inputs 
# and 100 is the dimensionality of the embedding vectors
print(embedded_output.shape)
print(embedded_output)

torch.Size([4, 6])
tensor([[-1.4395,  0.6494, -0.1276,  0.2380, -0.7978,  2.2173],
        [-0.1519,  0.7549,  0.2567, -0.6368, -1.9867,  0.0505],
        [-1.2726, -0.3244,  1.0599, -0.4081,  0.9614, -0.8176],
        [-0.4348,  1.4820, -0.2833,  1.7671,  0.0574,  0.3167]],
       grad_fn=<EmbeddingBackward0>)


In [134]:
a = torch.tensor([[1,2],[3,4],[5,6]])
b = torch.tensor([[7,8,9],[10,11,12]])
print (a@b)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


In [136]:
int_64 = torch.randint(1, (3,2)).float()
#type int64
float_32 = torch.rand(2,3)
#type of float32
#print(int_64.dtype, float_32.dtype)
result = torch.matmul(int_64,float_32)
print(result)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [138]:
a = torch.rand(2, 3, 5)
x, y, z =a.shape
a = a.view(x,y,z)
print(x,y,z)
print(a.shape)

2 3 5
torch.Size([2, 3, 5])


In [140]:
 input = torch.rand ((4,8,10))
B, T, C =input.shape
output = input.view(B*T, C)
print(output)
#print(input)
print(output[:, -1, :])

tensor([[0.6526, 0.3096, 0.2709, 0.2007, 0.9618, 0.2609, 0.2779, 0.2074, 0.4964,
         0.4150],
        [0.3535, 0.3492, 0.9606, 0.8388, 0.0886, 0.4680, 0.7366, 0.9235, 0.1906,
         0.4177],
        [0.7288, 0.0123, 0.4063, 0.9805, 0.2933, 0.9947, 0.3180, 0.9022, 0.5024,
         0.6934],
        [0.3950, 0.8552, 0.9384, 0.2818, 0.8736, 0.8895, 0.6120, 0.3762, 0.9752,
         0.7905],
        [0.8423, 0.5951, 0.9234, 0.4499, 0.4915, 0.4701, 0.1693, 0.1022, 0.6178,
         0.4800],
        [0.9292, 0.7800, 0.9582, 0.0614, 0.7399, 0.5327, 0.8360, 0.5356, 0.3059,
         0.3013],
        [0.1374, 0.2167, 0.8697, 0.0588, 0.1050, 0.2479, 0.6444, 0.1453, 0.2539,
         0.7881],
        [0.7490, 0.7880, 0.0206, 0.9361, 0.0693, 0.7459, 0.1060, 0.0962, 0.8323,
         0.4063],
        [0.4395, 0.3577, 0.5943, 0.9266, 0.3232, 0.4512, 0.7187, 0.3361, 0.6367,
         0.4585],
        [0.4628, 0.8705, 0.5872, 0.5267, 0.1766, 0.9174, 0.5881, 0.0259, 0.9110,
         0.5422],
        [0

IndexError: too many indices for tensor of dimension 2

In [104]:
x = torch.tensor([-0.05], dtype=torch.float32)
y = F.sigmoid(x)
print (y)

tensor([0.4875])
